### ISSUE TITLE
Replace PtoP form with a Start button and input wizard

### ISSUE THREAD

**Issue by andrewsage** [LivingKnowledgeNetwork/resolutionwallet#1]
Start button displays form and creates hash for the cycle:

* Set datamodel - formatted description (LKN-GATT- etc.) 
* Data validate - URI to data, once validated that the URI is present flag as okay
* Science validate - GitHub URL, once validated that URL is present flag as okay
* Compute validate - radio box of local, cloud, human, none - this is where the computation was run

All flags need to be set to true to allow sending to network.

**Comment by aboynejames** [comment]
Have given each bullet point an issue and this one left for the start button itself.

**Comment by aboynejames** [comment]
Added a UUID and display form with data- data ID to pickup for form.

Need to look again, at upgrading UUID to a 'transaction hash' to be decided.
